### ISSUE TITLE
Question: how to get GWMAC?

### ISSUE THREAD

**Issue by hawaii67** [scipag/nac_bypass#1]
First of all, it works fine, if the client and the DC are in separate subnets.
But how can you determine the GWMAC (gateway mac address) when the client and the DC are in the SAME subnet??

**Comment by 0x6d69636b** [comment]
That's a fair question and I don't have a general answer to that. However, if you are in a network with only one subnet, then the MAC address of the gateway is not relevant for internal communication and it might work without the correct MAC address. 

After that the interface is active and you can inspect further traffic and send packets yourself. Sooner or later you should be able to determine the MAC address for the gateway and configure the default routes manually.

That's my quick answer. But we will do our own research and, if possible, submit a solution later. Any suggestions are welcome... :-)

**Comment by hawaii67** [comment]
Well, the script tries to find (via tcpdump) and to set a GWMAC address in any case. 
Regarding my tests, you cannot connect to servers in the same subnet since your outgoing packets use as destination MAC the previously found and set GWMAC.
In my case it was the MAC of the DC - located in the same subnet. So I can connect to this DC but not to other servers in that same subnet.

**Comment by 0x6d69636b** [comment]
We'll investigate and get back to you. So to replicate this correctly, your setup was a subnet, e.g. 10.0.0.0/24, with a DC (as DHCP server) and other systems in the same subnet? The direct communication to systems in the subnet was not successful?

**Comment by hawaii67** [comment]
Yes, exactly. 
Because dest MAC ADDRESS (GWMAC) is alaways the same - that of the DC.

**Comment by 0x6d69636b** [comment]
I could reproduce your problem in my lab environment. A workaround would be to change the MAC address manually after executing the script: `arp -d -i $BRINT $BRGW $GWMAC_CORRECT`

However, I added an argument to set GWMAC manually from the start ([Commit 85ea51e](https://github.com/scipag/nac_bypass/commit/85ea51e2465fee78a338368918864758d0cc8d10)). 

Additionally you can control the tcpdump ports in the variables section, if you want to use protocols other than Kerberos or SMB ([Commit 7eb4e7a](https://github.com/scipag/nac_bypass/commit/7eb4e7ae6e1e3fa89a6ad25b79b7263180a75281)). An alternative would probably be HTTP and HTTPS, because there the chances are good that external pages are called directly via the gateway.

**Comment by hawaii67** [comment]
Thanks for getting back.
I didn't test it by now but could you connect to servers in the same subnet?
What is your default gateway, a router or a firewall?

**Comment by 0x6d69636b** [comment]
> I didn't test it by now but could you connect to servers in the same subnet?

Yes, after I used the MAC address of the router in the subnet. When the script gets the wrong MAC address, it was not possible. So I think basically you need to specify the MAC address of the system responsible for routing the subnet, whether it is a switch/firewall/router or not. This system will distribute all packets, whether inside the subnet or outside.

> What is your default gateway, a router or a firewall?

The gateway in my lab environment was a router/firewall combination.
